# -*- coding: utf-8 -*-
"""Database.sql

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1prcAjPNKRoTp3CID3kvyNzFY5AIpgA4j
"""

CREATE DATABASE perpustakaan;

USE perpustakaan;

CREATE TABLE buku
(
    id INT AUTO_INCREMENT PRIMARY KEY,
    judul VARCHAR(255),
    penulis VARCHAR(255),
    penerbit VARCHAR(255),
    tahun_terbit YEAR,
    konten TEXT,
    ikhtisar TEXT
);